enable-magisk-update = false

patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "Piko"

[X]
version = "10.49.0-release.0"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
